version: '3'

## Kafka & Zookeeper
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:3:1"
    depends_on:
      - "zookeeper"

## Producer


## Consumer
  consumer:
    image: tarosaiba/kafka-train-consumer
    environment:
      - KAFKA_BROKER=192.168.1.3:9092
      - KAFKA_TOPIC=test_topic

  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.0.0
    container_name: kafkarest
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_HOST_NAME: "kafkarest"
      KAFKA_REST_LISTENERS: "http://kafkarest:8082"
    depends_on:
      - "kafka"
      - "zookeeper"


# Viewere
 
## Kafka topi ui
  kafka-topic-ui:
    image: landoop/kafka-topics-ui:0.9.3
    environment:
      KAFKA_REST_PROXY_URL: "http://kafkarest:8082"
      PROXY: "true"
    ports:
      - "8000:8000"
    depends_on:
      - "kafka-rest"

## Kafka trifecta
  kafka-trifecta:
    image: janschultecom/docker-trifecta:latest
    environment:
      ZK_HOST: "zookeeper:2181"
    ports:
      - "9000:9000"
    depends_on:
      - "kafka"
      - "zookeeper"

## Kafka manager
  kafka-manager:
    image: sheepkiller/kafka-manager
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "letmein"
    ports:
      - "9090:9000"
    depends_on:
      - "kafka"
      - "zookeeper"
